config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'users/new'
  root 'tomato#home'
  get 'pomodoros/history'
  get 'pomodoros/spoiled'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
 
  resources :users


  post 'users/:id/update_password', to: 'users#update_password', as: "password_update"
  get 'users/:id/edit_password', to: 'users#edit_password', as: 'password_edit'
  
  resources :projects , only: [:new, :create] do |projects|
    resources :tasks, only: [:new, :create] do |tasks|
      resources :pomodoros
  end
end

  resources :password_resets 
end

app/models/task.rb
class Task < ActiveRecord::Base
	has_many :pomodoros
  belongs_to :project
  belongs_to :user
  belongs_to :project_id
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def new
    @task = Task.new
    @project = Project.find(params[:project_id])
    @pomodoro = Pomodoro.new
    @pomodoros = Pomodoro.daily_pomodoros(current_user)
    @projects = current_user.projects
    @tasks = current_user.tasks
  end

  def create
    t = Task.new(task_params)
    t.user = current_user
    t.project = Project.find(params[:project_id])
    t.save
    redirect_to new_project_task_pomodoro_url(t.project.id, t.id)
  end

  private
  def task_params
    params.require(:task).permit(:name)
  end
end

app/helpers/task_helper.rb
module TaskHelper
end

app/views/tasks/new.html.erb
<div class="col-sm-5 blog-main">
  <div class="done">
    <%= form_for(@task, url: project_tasks_url(@project)) do |f| %>
    <div class="field">
      <h3> SET TASK </h3>
      <%= f.text_field :name, :required => true %>
    </div>
    <% end %>
  </div>
</div>
<div class="col-md-5 col-md-offset-2 blog-sidebar">
  <div class="sidebar-module">
    <div class="daily-pomodoro">
      <div class="headline">
        <%= link_to new_project_path do %>
        <span class="button2" data-tooltip aria-haspopup="true" title="new project">+</span>
        <% end %>
      </div>
      <%= render "shared/form" %>
    </div>
  </div>
</div>