config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'users/new'
  root 'tomato#home'
  get 'pomodoros/history'
  get 'pomodoros/spoiled'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
 
  resources :users


  post 'users/:id/update_password', to: 'users#update_password', as: "password_update"
  get 'users/:id/edit_password', to: 'users#edit_password', as: 'password_edit'
  
  resources :projects , only: [:new, :create] do |projects|
    resources :tasks, only: [:new, :create] do |tasks|
      resources :pomodoros
  end
end

  resources :password_resets 
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :pomodoros
  has_many :projects
  has_many :tasks
	attr_accessor :remember_token
	before_save { self.email = email.downcase }
	validates :name, presence: true, length: { maximum: 50 }, uniqueness: true, :on => :update
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, length: { maximum: 255 }, uniqueness: true,:on => :update,
	format: { with: VALID_EMAIL_REGEX },
	uniqueness: { case_sensitive: false }
	has_secure_password
  validates :password, presence: true, confirmation: true, length: { minimum: 8 }

  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def authenticated?(remember_token)
  	return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  private
    def already_has_password?
       !self.password_digest.blank?
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, :except =>[:new, :create]
  skip_before_action :verify_authenticity_token

  def index
    @users = User.page(params[:page]).per(20).order("created_at DESC")
  end

  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
    @pomodoros = current_user.pomodoros.page(params[:page]).per(10).order("created_at DESC")
    @project = Project.new
    @pomodoro = Pomodoro.new
    @task = Task.new
    @projects = current_user.projects
    @tasks = current_user.tasks
  end

  def create
    @user = User.new(user_params)   
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "Welcome to the Pomodoro-Clock!"
      redirect_to user_url(@user.id)
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.authenticate(user_params[:password]) 
      if @user.update_attributes(edit_user_params)
        flash[:success] = "Profile updated"
        redirect_to @user
      else 
        render 'edit'
      end
    else
      flash.now[:danger] = "Authentication failed"
      render 'edit'
    end
  end

  def update_password
    @user = User.find(params[:id])
    if @user.authenticate(change_password_params[:current_password])
      @user.password = change_password_params[:new_password]
      @user.password_confirmation = change_password_params[:new_password_confirmation]
      if @user.save 
        flash[:success] = "Profile updated"
        redirect_to @user
      else 
        render 'edit_password'
      end
    else
      flash.now[:danger] = "Authentication failed"
      render 'edit_password'
    end
  end

  def edit_password
    @user = User.find(params[:id])
  end

  private

  def edit_user_params
    params.require(:user).permit(:name, :email)
  end

  def change_password_params
    params.permit(:current_password, :new_password, :new_password_confirmation)
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<div class="col-sm-6 blog-main">

 <div class="row">
  <div class="col-md-5 col-md-offset-2 blog-sidebar">
   <div class="sidebar-module">
    <h8>Update your profile</h8>
  
    <%= form_for(@user) do |f| %>
    <%= render 'shared/error_messages' %>
    
      <%= f.label :name, "NAME", class: "form_control" %>
      <%= f.text_field :name, class: "field_control" %>

      <%= f.label :email, "EMAIL", class: "form_control" %>
      <%= f.email_field :email, class: "field_control" %>

      <%= f.label :password, "PASSWORD", class: "form_control" %>
      <%= f.password_field :password, :placeholder => "confirm changes", class: "field_control" %>

      <br /> <br />
      <button type="submit" class="btn btn-default">Save changes</button>

     <% end %>
     <p>Want to change your password? <%= link_to "Change Password", password_edit_path %></p>
   </div>
 </div> 
</div>
</div>

app/views/users/edit_password.html.erb
<% provide(:title, "Edit password") %>
<div class="col-sm-6 blog-main">

 <div class="row">
  <div class="col-md-5 col-md-offset-2 blog-sidebar">
   <div class="sidebar-module">
    <h8>Update your password</h8>
    <%= form_tag(password_update_path(@user.id), method: 'post') do %>
    <%= render 'shared/error_messages' %>

      <%= label_tag :current_password, "CURRENT PASSWORD", class: "form_control" %>
      <%= password_field_tag :current_password, nil, class: "field_control"  %>

      <%= label_tag :new_password, "NEW PASSWORD", class: "form_control" %>
      <%= password_field_tag :new_password, nil, class: "field_control"  %>

      <%= label_tag :new_password_confirmation, "NEW PASSWORD CONFIRMATION", class: "form_control" %>
      <%= password_field_tag :new_password_confirmation, nil, class: "field_control" %>

      <br /> <br />
      <button type="submit" class="btn btn-default">Save changes</button>

     <% end %>
    <p>Want to change your name or email? <%= link_to "Update your profile", edit_user_path(current_user) %></p>
   </div>
 </div> 
</div>
</div>

app/views/users/index.html.erb
<html>
<body>
  <div class="col-sm-6 blog-main">
    <div class="row">
      <div class="col-sm-9 col-sm-offset-3">
    <h8>User</h8>
    <p> All</p>
       <%= paginate @users %>
       <table class="table">
        <tr>
         <th class= "col-sm-1"> User </th>
         <th class= "col-sm-1"> Name </th>
         <th class= "col-sm-1"> Email </th>
       </tr>

       <% @users.each do |user| %>
       <tr>
         <td><%= user.id %></td>
         <td><%= user.name %></td>
         <td><%= user.email %></td>
       </tr>
       <% end %>
     </table>
   </div>
 </div>
</div>
</body>
</html>

app/views/users/new.html.erb
<html>
<div class="col-sm-6 blog-main">
<div class="row">
  <div class="col-md-7 col-md-offset-3">
    <h8>User - Sign up</h8>
    <%= form_for(@user) do |f| %>
    <%= render 'shared/error_messages' %>
    
      <%= f.label :name, "NAME", class: "form_control" %>
      <%= f.text_field :name, class: "field_control" %>

      <%= f.label :email, "EMAIL", class: "form_control" %>
      <%= f.email_field :email, class: "field_control" %>

      <%= f.label :password, "PASSWORD", class: "form_control" %>
      <%= f.password_field :password, class: "field_control" %>

      <%= f.label :password_confirmation, "PASSWORD CONFIRMATION", class: "form_control" %>
      <%= f.password_field :password_confirmation, class: "field_control" %>
      
      <button type="submit" class="button">SIGN UP</button><br> </br>
      <a href="/login"><button class="button_second">LOG IN</button></a>

    <% end %>
  </div>
</div>
</div>
</html>

app/views/users/show.html.erb
<html>
<body>
<div class="col-sm-5 blog-main">
  <div class="done">
          <h4> Let's get </h4>
          <h5> started </h5>
          <h6> SET NEW PROJECT </h6>
          <%= link_to '+', new_project_path, class: 'round-button' %>
  </div>
</div>
<div class="col-md-5 col-md-offset-2 blog-sidebar">
  <div class="sidebar-module">
    <div class="daily-pomodoro">
      <div class="headline">
        <%= link_to new_project_path do %>
        <span class="button2" data-tooltip aria-haspopup="true" title="new project">+</span>
        <% end %>
      </div>
        <%= render "shared/form" %>
		</div>
	</div>
</body>
</html>