config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'users/new'
  root 'tomato#home'
  get 'pomodoros/history'
  get 'pomodoros/spoiled'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
 
  resources :users


  post 'users/:id/update_password', to: 'users#update_password', as: "password_update"
  get 'users/:id/edit_password', to: 'users#edit_password', as: 'password_edit'
  
  resources :projects , only: [:new, :create] do |projects|
    resources :tasks, only: [:new, :create] do |tasks|
      resources :pomodoros
  end
end

  resources :password_resets 
end

app/views/shared/_error_messages.html.erb
 <% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      Error 
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_form.html.erb
<nav class="pagination">
  <div class="project-list">
    <% @projects.each do |project| %>  
    <div class="project-name"> 
      <%= link_to new_project_task_path(project.id), style: 'color:#000' do %>
      <span data-tooltip aria-haspopup="true" title="add new task">
        <%= project.name %>
      </span>
      <% end %>
    </div>
    <div class="task-list">
      <% project.tasks.each do |task| %>  
      <p class="task-item"> 
        <%= link_to new_project_task_pomodoro_path(project.id, task.id), style: 'color:#000' do %>
        <% task.pomodoros.where(success: true).count.times do %>
        <%= image_tag("tomato_middle.png") %>
        <% end %>
        <% task.pomodoros.where(success: false).count.times do %>
        <%= image_tag("tomato_middle_spoiled.png") %>
        <% end %>
        <span data-tooltip aria-haspopup="true" title="add new pomodoro">
          <%= task.name %> 
        </span>
      </p>
      <% end %> 
      <% end %>
    </div> 
    <% end %> 
  </div>
</div>